import type { Metadata } from "next"
import { Inter, Playfair_Display } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Theme } from "@/providers/Theme"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "flex min-h-screen flex-col font-sans antialiased",
          inter.variable,
          playfair.variable
        )}
      >
        <Theme>
          <Header />
          <main className="grow">{children}</main>
          <Footer />
        </Theme>
      </body>
    </html>
  )
}

export default RootLayout
